name: 'Tagger Action'
description: 'Una acción compuesta que taggea una imagen'
inputs:
  user_name:
    description: 'Nombre del usuario'
    required: true
    default: 'default'
  app_version:
    description: 'Versión de la aplicación'
    required: true
    default: 'default'
  app_name:
    description: 'Nombre de la aplicación'
    required: true
    default: 'default'
  branch_name:
    description: 'Nombre de la rama de ejecución'
    required: true
    default: 'main'
outputs:
  image_name:
    description: 'Nombre de la imagen completa'
    value: ${{ steps.image_name_creator.outputs.image_name }}
runs:
  using: "composite"
  steps:
    - id: image_name_creator
      name: Extraer información sobre la versión del archivo JSON
      run: |
        if [[ ${{ inputs.branch_name }} = 'main' ]]; then
          image_name="${{ inputs.user_name }}/${{ inputs.app_name }}:${{ inputs.app_version }}"
        elif [[ ${{ inputs.branch_name }} = 'develop' ]]; then
          # image_name="${{ inputs.user_name }}/pre_${{ inputs.app_name }}:${{ inputs.app_version }}"
            image_name="${{ inputs.user_name }}/${{ inputs.app_name }}:${{ inputs.app_version }}-snapshot"
        fi
        
        echo "Esta es la imagen desde el action: ${image_name}"
        
        echo "image_name=${image_name}" >> $GITHUB_OUTPUT
      shell: bash
